### ISSUE TITLE
Suggestion: Only warn about insecure passwords

### ISSUE THREAD

**Issue by krischik** [alexpmorris/WhaleVault#3]
As someone who values freedom overt security I would prefer if you would not enforce strict password rules but only suggest that the password is not secure. It's not yours to decide which risks I am prepared to take.

**Comment by alexpmorris** [comment]
The password requirements including a "special character" originated from the original Steem Keychain version that WhaleVault is based on, so I guess they removed that constraint since then.

It sounds like it could be an issue with international keyboards, as I've seen that before.  it usually has to do with the user having set a different keyboard layout than the one used to set the password. While it could potentially affect any characters used, I did remove the *requirement* to use a "special character" in the latest release v0.1.43.

**Comment by krischik** [comment]
Thanks. Works better now.
